name: Atualizar URL HLS

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  push:
    paths:
      - update.py

jobs:
  update:
    runs-on: ubuntu-latest
   
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: python & yt-dlp
        run: |
          python -m pip install --upgrade pip yt-dlp

      - name: python
        run: python update.py

      - name: commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git diff
          git add url.txt
          git commit -m "update url" || echo "nothing to do"
          git push
